In [69]:
import numpy as np

In [70]:
# Создание массива 5x5 со случайными значениями.
array = np.random.randint(0, 100, size=(5, 5))
print("Исходный массив:\n", array)

Исходный массив:
 [[67 35 88 47 95]
 [33 33 70 82 43]
 [99 98 22 73 22]
 [93 98 64  3 90]
 [90 21 79 49 39]]


In [71]:
# Сортировка каждой строки по убыванию.
sorted_array = np.array([sorted(row, reverse=True) for row in array])

print("Отсортированный массив по каждой строке по убыванию:\n", sorted_array)


Отсортированный массив по каждой строке по убыванию:
 [[95 88 67 47 35]
 [82 70 43 33 33]
 [99 98 73 22 22]
 [98 93 90 64  3]
 [90 79 49 39 21]]
